/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import StudentIsA.*;
import SystemClassesAndMain.StudentSys;
import java.awt.event.KeyEvent;

/**
 *
 * @author Aizaz Hassan<Aizaz.Hassan>
 */
public class UndergraduateStudentFrame extends javax.swing.JFrame {

    /**
     * Creates new form StudentFrame
     */
    public UndergraduateStudentFrame() {
        initComponents();
    }

    public void clear() {
        txtId.setText("");
        txtName.setText("");
        txtSemesterNumber.setText("");
        txtSurname.setText("");
        txtYearOfAdmission.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnAddCourses = new javax.swing.JButton();
        txtYearOfAdmission = new javax.swing.JTextField();
        txtSurname = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtId = new javax.swing.JTextField();
        txtSemesterNumber = new javax.swing.JTextField();
        labelAlert = new javax.swing.JLabel();
        btnClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Add Undergraduate Student");

        jLabel1.setText("Student ID:");

        jLabel2.setText("Name:");

        jLabel3.setText("Surname:");

        jLabel4.setText("Year of Admission:");

        jLabel5.setText("Semester Number:");

        btnAddCourses.setText("ADD COURSES");
        btnAddCourses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCoursesActionPerformed(evt);
            }
        });

        txtSemesterNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSemesterNumberKeyPressed(evt);
            }
        });

        btnClose.setText("CLOSE");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(labelAlert, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtSemesterNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtYearOfAdmission)
                                    .addComponent(txtName)
                                    .addComponent(txtId, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                                    .addComponent(txtSurname)))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAddCourses, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtSurname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtYearOfAdmission, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtSemesterNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(labelAlert, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddCourses)
                    .addComponent(btnClose))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddCoursesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCoursesActionPerformed
        if (txtId.getText().isEmpty() || txtName.getText().isEmpty() || txtSemesterNumber.getText().isEmpty()
                || txtSurname.getText().isEmpty() || txtYearOfAdmission.getText().isEmpty()) {
            labelAlert.setText("Please fill all the fields!");
        } else {
            if (StudentSys.searchStudent(Integer.parseInt(txtId.getText())) != null) {
                labelAlert.setText("Student already exists!");
            } else {
                UndergraduateStudent u = new UndergraduateStudent(txtId.getText(),
                        txtName.getText(), txtSurname.getText(), txtYearOfAdmission.getText(),
                        txtSemesterNumber.getText());
                StudentSys.addStudent(u);
                AddCoursesFrame courseFrame = new AddCoursesFrame(this, u,null);
                courseFrame.setVisible(true);
                setVisible(false);
                labelAlert.setText(txtName.getText() + " " + txtSurname.getText() + " is added");
                clear();
            }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddCoursesActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        StudentSys.writeToFile();
        System.out.println(StudentSys.displayAll());
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCloseActionPerformed

    private void txtSemesterNumberKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSemesterNumberKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (txtId.getText().isEmpty() || txtName.getText().isEmpty() || txtSemesterNumber.getText().isEmpty()
                    || txtSurname.getText().isEmpty() || txtYearOfAdmission.getText().isEmpty()) {
                labelAlert.setText("Please fill all the fields!");
            } else {
                if (StudentSys.searchStudent(Integer.parseInt(txtId.getText())) != null) {
                    labelAlert.setText("Student already exists!");
                } else {
                    UndergraduateStudent u = new UndergraduateStudent(txtId.getText(),
                            txtName.getText(), txtSurname.getText(), txtYearOfAdmission.getText(),
                            txtSemesterNumber.getText());
                    StudentSys.addStudent(u);
                    AddCoursesFrame courseFrame = new AddCoursesFrame(this, u,null);
                    courseFrame.setVisible(true);
                    setVisible(false);
                    labelAlert.setText(txtName.getText() + " " + txtSurname.getText() + " is added");
                    clear();
                }
            }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSemesterNumberKeyPressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCourses;
    private javax.swing.JButton btnClose;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel labelAlert;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtSemesterNumber;
    private javax.swing.JTextField txtSurname;
    private javax.swing.JTextField txtYearOfAdmission;
    // End of variables declaration//GEN-END:variables
}
